SantinoMantineo/Lo-Canjeamos

- Server/.env
> first change

- Server/index.js
- Server/src/controllers/usersControllers.js
- Server/src/routes/userRoutes/userRoutes.js
meto PUT para users creado y funcionando
> Feature charly

- Client/src/App.jsx
- Client/src/components/Google/Google.jsx
- Client/src/components/Register/Register.jsx
- Client/src/components/navbar/Nabvar.jsx
- Client/src/views/Login/Login.jsx
- Client/src/views/myProfile/myProfile.jsx
adicional de agregar la view de formulario controlado realice redirecciones entre los componentes  views segun sea registrado o logeado
> se agrego formulario controlado de REGISTER

- Server/src/controllers/postsControllers.js
- Server/src/routes/postRoutes/postRoutes.js
Se agrega un endpoint que trae los posts filtrados por categoría.
> Endpoint filtro POSTS por categ

- Server/.env
- Server/src/controllers/postsControllers.js
- Server/src/routes/postRoutes/postRoutes.js
Agregamos al controller de post 2 funciones para obtener los post por Provincia o por Localidad.
> Ruta provincias/localidades

- Client/src/views/addProduct/addProduct.jsx
Se conectó el servicio de Cloudinary y el form envía correctamente la URL de la imagen al backend. 
**ADVERTENCIA:** de momento solo carga UNA sola imagen.
La cuenta de Cloudinary está con mi email.
> Imagen + Cloudinary (Una sola)

- Client/src/views/addProduct/addProduct.jsx
- Server/src/models/posts.js
Se trabajó en el formulario para crear Posts. Ahora envía multiples imágenes en un array al backend.
Para realizar esta acción se modificó el modelo de Posts en el backend, ahora la propiedad image es un array. (Tener en cuenta para cuando se quiera acceder a dicha propiedad).
> Form de Posts - Carga 3 Img - Cambio Modelo Posts

- Client/src/views/addProduct/addProduct.jsx
Ahora el formulario de Posts sube las imágenes tanto del explorador de archivos como al dropearlas en la zone. Falta agregarle estilos al campo.
Solo se modificó el archivo addProduct.
> Modif DropZone Formulario de Posts

- Client/src/components/card/card.jsx
> Image en la Card - Home

- Client/src/views/addProduct/addProduct.jsx
Se cambió la lógica del addProduct para implementar una nueva funcionalidad.
Ahora las imágenes no se suben a Cloudinary hasta el momento de darle al botón de "Crear Post". 
Además, se incorporó la posibilidad de eliminar las imágenes seleccionadas individualmente de tal manera que el usuario pueda borrar imágenes no deseadas o equivocadas.
Datos extra:
*El addProduct demora unos segundos hasta que devuelve el alert("Producto creado correctamente").
*Ya no se puede seleccionar cualquier tipo de archivo, solo aquellos con formato de imagen.
> Cambio de lógica en el addProduct

- Client/src/components/modal/Modal.jsx
- Client/src/components/modal/Modal.module.css
- Client/src/views/addProduct/addProduct.jsx
Se agregó un pequeño modal (componente pop-up) que se renderiza al finalizar la creación de una publicación/posts.
Se puede clickear tanto en la X como fuera del mensaje para que se cierre.
> Modal para el addProduct

- Client/src/views/login/Login.jsx
Login validation. Quiero mejorarlo pero funciona
> Login validation

- Server/node_modules/.package-lock.json
- Server/package-lock.json
- Server/package.json
- Server/src/config/mailer.js
- Server/src/controllers/usersControllers.js
- Server/src/utils/mailObjects.js
Se utilizó 'nodemailer' para agregar las notificaciones por mail.
**De momento:** solo envía un mail al momento de registrar un usuario.
PD: Habría que agregar las credenciales de auth al .env para no especificar la contraseña directamente.
> Notificación por Mail al registrarse

- Client/src/views/login/validate.js
- Server/src/controllers/usersControllers.js
- Server/src/routes/userRoutes/userRoutes.js
forgot y reset de contraseñas casi terminado, solo falta utilizar nodemailer
> forgot/reset PASSWORD

- Client/src/App.jsx
- Client/src/components/forgotPassword/ForgotPassword.jsx
- Client/src/components/forgotPassword/ForgotPassword.module.css
- Client/src/components/resetPassword/ResetPassword.jsx
- Client/src/components/resetPassword/ResetPassword.module.css
- Client/src/views/login/Login.jsx
he creado el componente resetPassword y forgotPassword para recuperar la contraseña
> olvido su contraseña? parte front

- Server/src/controllers/postsControllers.js
- Server/src/utils/mailObjects.js
- Server/src/utils/register.html
Se agregó un template personalizado para el mail que llega al momento de registrarse. (Puede mejorar).
2do commit: se agregó un mail para cuando se crea una publicación (no template).
> Template para el mail al registrarse.

- Client/src/components/register/Register.jsx
- Server/src/controllers/usersControllers.js
Se cambió el tipo de input al momento de Registrarse. Ahora es un input de tipo _image_ el cual permite seleccionar un archivo de tipo imagen así como eliminarlo y cargar uno nuevo. 
Esta imagen se carga en Cloudinary al momento de submitear y registrarse.
Falta hacer que el Perfil adopte dicha imagen.
> Register con Imagen + Cloudinary

- Client/src/App.jsx
- Client/src/components/forgotPassword/ForgotPassword.jsx
- Client/src/components/resetPassword/ResetPassword.jsx
- Client/src/components/resetPassword/validate.js
- Server/src/controllers/usersControllers.js
- Server/src/utils/mailObjects.js
Recuperacion contraseña/ validaciones para resetpassword
> Recuperacion de contrasena

- Client/src/components/forgotPassword/ForgotPassword.jsx
> arreglo mini error

- Client/package-lock.json
- Client/package.json
- Client/src/components/register/Register.jsx
- Client/src/components/register/validations.js
- Client/src/views/login/validate.js
Form de registro y validaciones
> form y validaciones

- Client/src/views/addProduct/AddProduct.module.css
- Client/src/views/addProduct/addProduct.jsx
Se modificó el archivo addProduct. Al momento de darle click al botón de 'Crear' ocurre lo siguiente:
* Se deshabilitan todos los campos incluyendo el botón mismo de 'Crear'.
* Aparece un spinner y un texto indicando que se está cargando la publicación.
De esta manera el usuario tiene noción de que su publicación está siendo cargada y además se quita la posibilidad de que pueda darle 'Crear' más de una vez hasta que su publicación se haya cargado.
> Loading en addProduct + Disabled button

- Client/src/components/matchs/Matchs.jsx
- Client/src/views/chats/chats.jsx
- Client/src/views/detail/Detail.jsx
- Client/src/views/detail/Detail.module.css
- Server/package-lock.json
boton "canje" desabilitado si es tu publi - - alert si no tenes elegi
da una publi al dar "canje"
> boton "canje" desabilitado si es tu publi - - alert si no tenes elegi da una publi al dar "canje"

- Client/src/components/register/Register.jsx
- Client/src/components/register/Register.module.css
Se implementó el spinner de carga en el formulario de registro. Ahora cuando el usuario oprime el botón de 'Enviar', visualiza esa pequeña carga hasta que recibe la notificación de Registro Exitoso.
PD: Se eliminó todo el componente que estaba comentado en Register.jsx
> Loading en Register

- Client/src/App.jsx
- Client/src/components/avatar/Avatar.module.css
- Client/src/components/publication/Publication.module.css
- Client/src/components/register/Register.module.css
- Client/src/views/addProduct/addProduct.jsx
- Client/src/views/myProfile/MyProfile.module.css
- Server/serverConfig.js
- Server/src/DB_config.js
> Maxi domingo

- Client/package.json
- Client/src/views/login/Login.jsx
- Client/src/views/login/validate.js
> alert login

- Client/src/components/forgotPassword/ForgotPassword.jsx
- Client/src/components/resetPassword/ResetPassword.jsx
- Server/serverConfig.js
- Server/src/DB_config.js
- Server/src/utils/mailObjects.js
adicional ya solo se envia un   correo diferente por cada solicitud de recuperacion de contraseña
> agrege alerts en forgotpassword y resetpassword,

- Server/src/utils/forgot.html
- Server/src/utils/mailObjects.js
- Server/src/utils/newPost.html
Se cambiaron las notificaciones por mail, agregando un estilo más sencillo pero prolijo con un botón de redirección. En este momento hay notificaciones por correo para:
* Registro.
* Reestablecer contraseña.
* Crear una publicación.
**ESTAS SOLO FUNCIONAN PARA EL DEPLOY.** Se debe cambiar el archivo 'mailObjects' si se quieren enviar mails para localhost.
No pudimos implementar la notificación para los Matches.
> Cambio en las notif. por Mail

- Client/src/views/addProduct/addProduct.jsx
- Client/src/views/addProduct/validation.js
> alerts addproduct

- Client/src/App.jsx
- Client/src/components/avatar/Avatar.module.css
- Client/src/components/chats/ChatsMessages.jsx
- Client/src/components/chats/ChatsMessages.module.css
- Client/src/components/publication/Publication.jsx
- Client/src/views/chats/chats.jsx
- Client/src/views/detail/Detail.jsx
- Server/index.js
Arreglos menores de css en los chats, circulo azul para la seleccion de publicaciones.
> Maxi domingo2

- Server/src/controllers/usersControllers.js
- Server/src/models/posts.js
- Server/src/models/user.js
- Server/src/routes/userRoutes/userRoutes.js
* Se agregó el atribuito _'paranoid'_ a los modelos de Users y de Posts para así poder realizar soft-delete en ambas tablas.
* Se agregó la ruta para obtener todos los usuarios deshabilitados junto con su controller.
* Se agregó la ruta para restaurar un usuario a través de su ID junto con su controller.
! **FALTA** agregar las rutas y controllers para Posts.
> Paranoid + Handler & Controller Users

- Client/src/views/detail/Detail.jsx
boton siguiente y anterior sirve para hacer la navegacion, solo toque el componente detail y no quite nada solo agrege mi codigo para que navege
> navegacion en el Detail,

- Server/src/controllers/usersControllers.js
- Server/src/routes/userRoutes/userRoutes.js
Corregidos el Handler y el Controller del borrado lógico. 
**Se encuentran funcionando (backend) ✅**
> Soft-Delete Fixed (Backend working)

- Client/src/components/register/Register.jsx
- Client/src/views/detail/Detail.jsx
- Server/src/controllers/usersControllers.js
Alerts del registers terminadas, usercontroller createUser modificado y redireccion boton en detail arreglado
> Alert ya existe user/email y redireccion boton en detail

- Client/src/components/likedPosts/PostsLiked.jsx
- Server/src/controllers/postsControllers.js
- Server/src/routes/postRoutes/postRoutes.js
* Se agregó la ruta para restaurar publicaciones.
* Se agregó el controller para restaurar publicaciones.
* Se corrigió un pequeño **BUG** en el componente 'LikedPosts' que no cargaba la imagen cuando la publicación contenía más de una imagen (ahora carga la primera).
> Soft-Del - Ruta y Controller para Posts - LikedImg

- Client/src/components/chats/ChatsMessages.jsx
- Client/src/components/chats/ChatsMessages.module.css
- Client/src/views/Messages/Messages.jsx
- Client/src/views/Messages/Messages.module.css
> Maxi miercoles

- Client/src/views/detail/Detail.jsx
para esta modificacion solo se toco el datail en las funciones que manejan las flechas de ir adelante y atras
>  detail ya trae los id de forma ordenada asendente y desendente

- Client/src/redux/actionTypes.js
- Client/src/redux/actions.js
- Client/src/redux/reducer.js
- Server/src/controllers/postsControllers.js
- Server/src/controllers/usersControllers.js
Se agregaron Action-Types, Actions y se modificó el Reducer para llevar a cabo el Soft-Delete.
- Action y Reducer para **RESTAURAR** un usuario luego de ser deshabilitado.
- Action y Reducer para **RESTAURAR** una publicación luego de ser deshabilitada.
- Action y Reducer para **OBTENER** todos los usuarios deshabilitados.
- Action y Reducer para **OBTENER** todas las publicaciones deshabilitadas.
- Se modificó la respuesta de los controllers para restaurar tanto _Usuarios_ como _Publicaciones._ Ahora devuelven el elemento restaurado para así, posteriormente, agregarlos al array del front con los demás elementos.
> Redux (Soft-Delete) -  Respuesta en Controllers

- Client/src/App.jsx
- Client/src/components/avatar/Avatar.jsx
- Client/src/components/avatar/Avatar.module.css
- Client/src/components/filters/Filters.module.css
- Client/src/components/matchs/Matchs.jsx
- Client/src/components/publication/Publication.module.css
- Client/src/components/recivedLikes/recivedLikes.jsx
- Client/src/components/recivedLikes/recivedLikes.module.css
- Client/src/views/exchanges/Exchanges.module.css
- Client/src/views/myProfile/MyProfile.module.css
- Server/src/DB_config.js
> Maxi jueves

- Client/src/App.jsx
- Client/src/components/likedPosts/PostsLiked.jsx
- Client/src/components/recivedLikes/recivedLikes.jsx
- Client/src/views/exchanges/Exchanges.module.css
- Client/src/views/exchanges/exchanges.jsx
- Client/src/views/myProfile/myProfile.jsx
- Server/index.js
> Maxi viernes

- Client/src/views/addProduct/addProduct.jsx
Alert y redireccion desde la alrert a mercado pago. Cambio de 1500 milisegundos a apretar el boton para volver al perfil
> alertas en add product

- Server/src/controllers/reviewsController.js
- Server/src/models/reviews.js
- Server/src/routes/reviewsRoutes/reviewsRoutes.js
- Server/src/routes/routes.js
Cree modelo para las reviews, controller y rutas.
> back de las reviews

- Client/src/views/addProduct/addProduct.jsx
- Server/src/DB_config.js
- Server/src/controllers/reviewsController.js
- Server/src/models/user.js
- Server/src/routes/reviewsRoutes/reviewsRoutes.js
Back de las reviews listo. Modelo User modificado
> back reviews listo

- Server/src/controllers/matchControllers.js
- Server/src/controllers/usersControllers.js
- Server/src/models/matches.js
- Server/src/routes/userRoutes/userRoutes.js
- Server/src/utils/mailObjects.js
- Server/src/utils/matchTemplate.html
Se agregó correctamente el mail para cuando existe un Match nuevo. Dicho mail solo se crea una vez tras almacenarse en una tabla en la base de datos. Detallo cambios:
* Al momento de agregar un Match al array de Matches, se verifica si dicho Match se encuentra en la base de datos. En caso de que no, se envía el mail. Esto previene enviar el mail en reiteradas ocasiones.
* Se creó un modelo 'Matches' en la base de datos que almacena los mismos.
* Se creó un template para el mail de Matches con un botón que redirige a la pestaña 'Canjes' en la web.
> Mails para Matches

- Client/src/components/filters/filters.jsx
- Client/src/views/detail/Detail.jsx
Arreglado orden de navegacion en los botones de detail
> botones navegacion datail

- Client/src/App.jsx
- Client/src/views/adminDash/AdminDash.jsx
- Server/src/DB_config.js
Cambie todas las alerts de la admindash.
> alerts a admindash

- Client/src/components/register/Register.jsx
- Client/src/views/addProduct/addProduct.jsx
- Client/src/views/addProduct/validation.js
Ultimos cambios del formulario addProduct y del register
> register listo

- Client/src/components/allCards/AllCards.jsx
- Client/src/views/home/home.jsx
> Paginado Ahora si BB
